.PHONY: install install-user

install:
	jupyter nbextension install klampt/
	jupyter nbextension enable klampt/main
	jupyter nbextension enable klampt/three.min
	jupyter nbextension enable klampt/KlamptFrontend

install-user:
	jupyter nbextension install klampt/ --user
	jupyter nbextension enable klampt/main 
	jupyter nbextension enable klampt/three.min 
	jupyter nbextension enable klampt/KlamptFrontend 
